name: WPCS Check
on: [push, pull_request]

jobs:
  linter:
    runs-get: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv

      - name: Install WordPress Coding Standards
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHPCS
        run: phpcs --standard=WordPress ./page-porter-for-elementor.php
